console.log(Date())

let fecha = new Date()
console.log(fecha)

console.log(fecha.getDate())
console.log(fecha.getDay())
console.log(fecha.getMonth())
console.log(fecha.getFullYear())
console.log(fecha.getHours())
console.log(fecha.getMinutes())
console.log(fecha.getSeconds())
console.log(fecha.toString())
console.log(fecha.toDateString())
console.log(fecha.toLocaleString())
console.log(fecha.toLocaleDateString())
console.log(fecha.toLocaleTimeString())
console.log(fecha.getTimezoneOffset())
console.log(fecha.getUTCHours())
console.log(Date.now())

let cumpleShane = new Date(1997, 6, 7)
console.log(cumpleShane)